// <auto-generated />
namespace AtendimentoOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_bancoAten : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_bancoAten));
        
        string IMigrationMetadata.Id
        {
            get { return "201702071917313_db_bancoAten"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
